/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\src\components\HeroModels\insanity_in_motion.glb 
Author: Miguelangelo Rosario (https://sketchfab.com/miguelangelo2k)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/insanity-in-motion-e6800fce182747ad8b20b1f4c0f430e6
Title: INSANITY IN MOTION
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/insanity_in_motion.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.009}>
          <group name="970c1c501f1441b5b553c13f2b647d41fbx" rotation={[-Math.PI, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Group004" position={[-155.242, -3342.746, 255.488]} scale={0.1}>
                  <group name="Object_5">
                    <group name="hero" position={[802.044, 33470.844, -2554.875]} scale={494.234} />
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_7" scale={49.423} />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['02_-_Default']} skeleton={nodes.Object_8.skeleton} />
                  </group>
                </group>
                <group name="Torus001" position={[1387.319, -2.956, 187.814]} scale={0.1}>
                  <group name="Sphere001" position={[-1987.258, 14826.023, 1867.428]} rotation={[Math.PI, 0, -1.501]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_126" position={[0, -0.001, -657.278]}>
                      <mesh name="Sphere001_11_-_Default_0" geometry={nodes['Sphere001_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere002" position={[5692.008, 13833.338, 1867.428]} rotation={[Math.PI, 0, -0.977]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_129" position={[0, -0.001, -657.278]}>
                      <mesh name="Sphere002_11_-_Default_0" geometry={nodes['Sphere002_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere003" position={[11846.1, 9134.008, 1867.428]} rotation={[Math.PI, 0, -0.454]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_132" position={[0, 0.001, -657.278]}>
                      <mesh name="Sphere003_11_-_Default_0" geometry={nodes['Sphere003_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere004" position={[14826.029, 1987.22, 1867.428]} rotation={[-Math.PI, 0, 0.07]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_135" position={[0, 0, -657.278]}>
                      <mesh name="Sphere004_11_-_Default_0" geometry={nodes['Sphere004_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere005" position={[13833.322, -5692.043, 1867.428]} rotation={[-Math.PI, 0, 0.593]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_138" position={[0.004, -0.001, -657.278]}>
                      <mesh name="Sphere005_11_-_Default_0" geometry={nodes['Sphere005_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere006" position={[9133.977, -11846.124, 1867.428]} rotation={[-Math.PI, 0, 1.117]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_141" position={[0, 0, -657.278]}>
                      <mesh name="Sphere006_11_-_Default_0" geometry={nodes['Sphere006_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere007" position={[1987.182, -14826.034, 1867.428]} rotation={[-Math.PI, 0, 1.641]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_144" position={[0.004, 0, -657.278]}>
                      <mesh name="Sphere007_11_-_Default_0" geometry={nodes['Sphere007_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere008" position={[-5692.08, -13833.309, 1867.428]} rotation={[-Math.PI, 0, 2.164]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_147" position={[-0.004, 0, -657.278]}>
                      <mesh name="Sphere008_11_-_Default_0" geometry={nodes['Sphere008_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere009" position={[-11846.148, -9133.947, 1867.428]} rotation={[-Math.PI, 0, 2.688]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_150" position={[-0.004, 0.001, -657.278]}>
                      <mesh name="Sphere009_11_-_Default_0" geometry={nodes['Sphere009_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere010" position={[-14826.039, -1987.144, 1867.428]} rotation={[Math.PI, 0, -3.072]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_153" position={[0, 0, -657.278]}>
                      <mesh name="Sphere010_11_-_Default_0" geometry={nodes['Sphere010_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere011" position={[-13833.295, 5692.115, 1867.428]} rotation={[Math.PI, 0, -2.548]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_156" position={[0, 0, -657.278]}>
                      <mesh name="Sphere011_11_-_Default_0" geometry={nodes['Sphere011_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="Sphere012" position={[-9133.939, 11846.153, 1867.428]} rotation={[Math.PI, 0, -2.025]} scale={[0.438, 0.438, 0.247]}>
                    <group name="Object_159" position={[0, 0, -657.278]}>
                      <mesh name="Sphere012_11_-_Default_0" geometry={nodes['Sphere012_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
                    </group>
                  </group>
                  <group name="sign" position={[-0.003, 0.001, 0]}>
                    <mesh name="sign_04_-_Default_0" geometry={nodes['sign_04_-_Default_0'].geometry} material={materials['04_-_Default']} />
                  </group>
                  <group name="kroko" position={[0.001, 0, 0]}>
                    <mesh name="kroko_05_-_Default_0" geometry={nodes['kroko_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                  </group>
                  <group name="krokol">
                    <mesh name="krokol_06_-_Default_0" geometry={nodes['krokol_06_-_Default_0'].geometry} material={materials['06_-_Default']} />
                  </group>
                  <group name="logosmall" position={[-0.002, 0.002, 0]}>
                    <mesh name="logosmall_07_-_Default_0" geometry={nodes['logosmall_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                  </group>
                  <group name="plak" position={[0, 0.001, 0]}>
                    <mesh name="plak_08_-_Default_0" geometry={nodes['plak_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
                  </group>
                  <group name="mso" position={[0.002, -0.001, 0]} rotation={[0, 0, -0.009]}>
                    <mesh name="mso_09_-_Default_0" geometry={nodes['mso_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                  </group>
                  <group name="mso001" position={[0.001, 0.001, 0]}>
                    <mesh name="mso001_10_-_Default_0" geometry={nodes['mso001_10_-_Default_0'].geometry} material={materials['10_-_Default']} />
                  </group>
                  <group name="floor" position={[-0.001, -0.001, 0]}>
                    <mesh name="floor_12_-_Default_0" geometry={nodes['floor_12_-_Default_0'].geometry} material={materials['12_-_Default']} />
                  </group>
                  <group name="sign001" position={[-15423.641, -5512.063, -6.06]}>
                    <group name="Object_164" position={[15423.641, 5512.063, -117.927]}>
                      <mesh name="sign001_13_-_Default_0" geometry={nodes['sign001_13_-_Default_0'].geometry} material={materials['13_-_Default']} />
                    </group>
                  </group>
                  <mesh name="Torus001_03_-_Default_0" geometry={nodes['Torus001_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                </group>
                <group name="Camera001" position={[-105.047, 661.049, 137.538]} rotation={[-Math.PI / 2, -0.014, -Math.PI]} scale={0.1}>
                  <group name="Object_107" />
                </group>
                <group name="Camera001Target" position={[-76.815, -1301.084, 137.538]} scale={0.1} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/insanity_in_motion.glb')
